// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
    name: "PlotLab",
    platforms: [
        .iOS("18.0"),
    ],
    products: [
        .iOSApplication(
            name: "PlotLab",
            targets: ["AppModule"],
            bundleIdentifier: "com.phanuphats.PlotLab",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown,
                .landscapeRight,
                .landscapeLeft,
            ],
            appCategory: .education
        ),
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        ),
    ],
    swiftLanguageModes: [.version("6")]
)
